## Server
#server.port=8084
#spring.application.name=hrms-backend
#
## MySQL Database
#spring.datasource.url=jdbc:mysql://localhost:3306/WorkSphere?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
## JWT Configuration
#jwt.secret=HRMS_SuperSecretKey_ForJWT_Token_Generation_2024_Minimum256Bits!!
#jwt.expiration=86400000
#
## CORS
#cors.allowed-origins=http://localhost:5173,http://localhost:3000
#
## File Upload
#spring.servlet.multipart.max-file-size=5MB
#spring.servlet.multipart.max-request-size=5MB
#
## Logging
#logging.level.com.hrms=DEBUG
#logging.level.org.springframework.security=INFO

#=======================================================================AvIEN CHNGE 


server.port=${PORT:10000}
spring.application.name=hrms-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

logging.level.com.hrms=INFO
logging.level.org.springframework.security=INFO